In [1]:
import pandas as pd
import numpy as np
event_df = pd.read_csv('events.csv')
event_df

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,2228777,NaN,3,c13fd8d6-3124-4628-903a-9f504408c6a8,2024-01-05 10:31:00 UTC,55.163.67.120,Morioka City,Iwate,020-0866,Chrome,Email,/cancel,cancel
1,1600901,NaN,3,24447ec0-f65f-4217-8749-87684cd1e6e6,2022-02-11 10:54:00 UTC,29.183.158.20,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
2,1957273,NaN,3,c24ae5ea-5602-46d4-8e3d-3810bea85dcb,2025-01-07 04:20:00 UTC,147.51.19.159,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
3,1659964,NaN,3,20483386-febf-4778-80aa-c9ffb2247080,2022-10-18 04:22:00 UTC,79.4.214.192,São Paulo,São Paulo,02675-031,Chrome,Adwords,/cancel,cancel
4,1710934,NaN,3,abd75ce1-9ffa-432c-b656-aa5ca07f0500,2025-02-17 13:58:00 UTC,2.193.71.136,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2429727,898472,68767.0,7,83fbfe15-18e2-49ab-afac-338c70b44916,2019-07-18 10:35:42 UTC,68.155.123.60,Crofton,England,WF4,Firefox,Email,/purchase,purchase
2429728,1244640,95462.0,13,56e02878-60ca-4655-9788-3450b8ad397b,2025-11-13 19:12:28 UTC,128.236.248.69,Wigan,England,WN3,Chrome,Adwords,/purchase,purchase
2429729,1255821,96347.0,5,d7f98019-1a3e-410b-aeae-7cf56ee90d60,2023-06-02 18:03:19 UTC,194.246.12.129,Evesham,England,WR11,Firefox,Organic,/purchase,purchase
2429730,1275524,97828.0,5,2d17565f-f5e4-49eb-93b1-589ba0eb4b85,2024-04-28 00:09:26 UTC,46.120.86.159,Wolverhampton,England,WV11,Firefox,Email,/purchase,purchase
2429731,142628,11086.0,5,c8632f64-270e-4e53-80aa-31a5d57aa7c7,2025-11-06 23:55:46 UTC,47.250.21.234,York,England,YO30,Firefox,Facebook,/purchase,purchase

In [2]:
event_df.dtypes

id                   int64
user_id            float64
sequence_number      int64
session_id          object
created_at          object
ip_address          object
city                object
state               object
postal_code         object
browser             object
traffic_source      object
uri                 object
event_type          object
dtype: object

In [3]:
event_df.isna().sum()

id                       0
user_id            1126150
sequence_number          0
session_id               0
created_at               0
ip_address               0
city                 22491
state                    0
postal_code              0
browser                  0
traffic_source           0
uri                      0
event_type               0
dtype: int64

In [4]:
event_df['event_type'].value_counts().sort_index(ascending=True)

event_type
cancel        125389
cart          594995
department    594958
home           88046
product       844596
purchase      181748
Name: count, dtype: int64

In [5]:
#user_id가 결측치인유저의 행동(비회원인지 확인)
event_df[event_df['user_id'].isna()]['event_type'].value_counts()

event_type
product       500000
cart          250399
department    250362
cancel        125389
Name: count, dtype: int64

In [6]:
# user_id의 null 값을 0으로 채우기
event_df['user_id'] = event_df['user_id'].fillna(0)
# user_id가 0인값(비회원)따로 저장
non_member_df = event_df[event_df['user_id'] == 0]
non_member_df

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,2228777,0.0,3,c13fd8d6-3124-4628-903a-9f504408c6a8,2024-01-05 10:31:00 UTC,55.163.67.120,Morioka City,Iwate,020-0866,Chrome,Email,/cancel,cancel
1,1600901,0.0,3,24447ec0-f65f-4217-8749-87684cd1e6e6,2022-02-11 10:54:00 UTC,29.183.158.20,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
2,1957273,0.0,3,c24ae5ea-5602-46d4-8e3d-3810bea85dcb,2025-01-07 04:20:00 UTC,147.51.19.159,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
3,1659964,0.0,3,20483386-febf-4778-80aa-c9ffb2247080,2022-10-18 04:22:00 UTC,79.4.214.192,São Paulo,São Paulo,02675-031,Chrome,Adwords,/cancel,cancel
4,1710934,0.0,3,abd75ce1-9ffa-432c-b656-aa5ca07f0500,2025-02-17 13:58:00 UTC,2.193.71.136,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427874,1737383,0.0,1,f806028d-5974-40ab-b51f-47bfd1ca9050,2024-01-18 07:59:00 UTC,186.178.99.30,Hednesford,England,WS12,Other,Adwords,/product/5706,product
2427875,2137124,0.0,1,9aa6c6b7-56d7-44a1-94dc-c22704b004be,2022-10-19 15:13:00 UTC,206.37.95.210,Lichfield,England,WS13,Chrome,Adwords,/product/24056,product
2427878,2110151,0.0,2,4bbf6650-78f3-4ab6-84d9-91a7ababa9ce,2023-06-24 05:01:00 UTC,202.245.196.114,Wolverhampton,England,WV10,Firefox,YouTube,/product/5025,product
2427879,2145320,0.0,1,470696a4-39e1-4991-abc6-f7e6ab07adeb,2019-07-03 06:14:00 UTC,154.222.44.62,Wolverhampton,England,WV11,Safari,YouTube,/product/13579,product
2427880,2399658,0.0,1,e2897701-f6f9-47c4-889f-1035ff84fa69,2019-10-21 17:57:00 UTC,24.215.84.244,Driffield,England,YO25,Safari,Email,/product/17126,product

In [7]:
# 'city' 컬럼이 null인 행만 골라서 삭제
event_df = event_df.dropna(subset=['city'])

In [8]:
event_df.isna().sum()

id                 0
user_id            0
sequence_number    0
session_id         0
created_at         0
ip_address         0
city               0
state              0
postal_code        0
browser            0
traffic_source     0
uri                0
event_type         0
dtype: int64

In [ ]:
===============================================events테이블 전처리 완료=================================

In [9]:
import pandas as pd
import numpy as np
initems_df = pd.read_csv('inventory_items.csv')
initems_df

,id,product_id,created_at,sold_at,cost,product_category,product_name,product_brand,product_retail_price,product_department,product_sku,product_distribution_center_id
0,18988,13844,2024-07-18 08:26:30 UTC,2024-09-13 21:58:30 UTC,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
1,18989,13844,2022-09-30 14:02:00 UTC,NaN,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
2,98138,13844,2025-08-04 07:18:50 UTC,2025-09-29 01:29:50 UTC,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
3,98139,13844,2020-02-23 04:34:00 UTC,NaN,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
4,234601,13844,2022-08-03 15:42:36 UTC,2022-08-15 15:20:36 UTC,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
...,...,...,...,...,...,...,...,...,...,...,...,...
490502,359148,25590,2025-07-15 17:05:43 UTC,2025-09-02 08:39:43 UTC,10.39200,Underwear,ck one Men's Micro Slim Fit Boxer,Calvin Klein,24.00,Men,F220707C3AFE39D1779E0A34AF72BB7F,3
490503,359149,25590,2022-06-27 11:30:00 UTC,NaN,10.39200,Underwear,ck one Men's Micro Slim Fit Boxer,Calvin Klein,24.00,Men,F220707C3AFE39D1779E0A34AF72BB7F,3
490504,462494,25590,2022-06-07 10:10:50 UTC,2022-06-29 18:23:50 UTC,10.39200,Underwear,ck one Men's Micro Slim Fit Boxer,Calvin Klein,24.00,Men,F220707C3AFE39D1779E0A34AF72BB7F,3
490505,462495,25590,2020-12-24 17:25:00 UTC,NaN,10.39200,Underwear,ck one Men's Micro Slim Fit Boxer,Calvin Klein,24.00,Men,F220707C3AFE39D1779E0A34AF72BB7F,3
490506,462496,25590,2024-11-09 12:24:00 UTC,NaN,10.39200,Underwear,ck one Men's Micro Slim Fit Boxer,Calvin Klein,24.00,Men,F220707C3AFE39D1779E0A34AF72BB7F,3

In [14]:
# 브랜드명 대문자로 바꿈(소문자도 좋음)
initems_df['product_brand'] = initems_df['product_brand'].str.upper()

In [15]:
initems_df['product_brand'].value_counts(ascending=True).head(50)

product_brand
SGT FROG                  2
EVA VARRO                 2
PISTOL PETE UNDERWEAR     2
ONE TEASPOON              2
COLORADO CLOTHING         2
SABREE                    2
AMETHYST JEANS            3
DESSY                     3
SNOB                      3
WESTON WEAR               3
HOLLYWOOD MIRROR          4
ALI RO                    4
YALA DESIGNS              4
HYDRAULIC                 4
GPUFASHION                4
TIE-DYES                  4
ESCARGOT SPORTSWEAR       4
PURPLETOPIA               4
CONNECTED                 4
DOLPHIN SHIRT CO          4
SERENGETI                 4
CHOYE TOI                 4
SOLID COLOR               4
JSLV                      4
BHPC BY MISS LONDON       4
MIRACLEBODY               4
PPU                       4
ACNE                      5
RAILS                     5
BABOOSH                   5
COOL KAFTANS              5
ULTRASOFTS BY NATIONAL    5
ARIZONA                   5
RAY&LI                    5
MATERIAL GIRL             5
PLEJUE                    5
CALIDA                    5
JET                       5
POLO JEANS CO.            6
MUMMY DARLING             6
EXPRESSIVA NURSINGWEAR    6
CTR SPECIALTIES           6
WEMBLEY                   6
BACK TO NATURE            6
ONE STEP UP PLUS          6
NECESSARY OBJECTS         6
VOCAL                     6
WOLFORD                   6
NYFASHION101              6
MODUS VIVENDI             6
Name: count, dtype: int64

In [16]:
initems_df['product_brand'].value_counts(ascending=False).head(50)

product_brand
ALLEGRA K               16758
CALVIN KLEIN             8945
CARHARTT                 6931
VOLCOM                   5166
HANES                    5107
QUIKSILVER               4822
NAUTICA                  4811
TOMMY HILFIGER           4458
LEVI'S                   4282
DOCKERS                  4073
DIESEL                   4028
COLUMBIA                 3998
HURLEY                   3980
WRANGLER                 3357
SPEEDO                   3185
LUCKY BRAND              3060
DICKIES                  3018
AMERICAN APPAREL         2989
CHAMPION                 2983
7 FOR ALL MANKIND        2943
MOTHERHOOD MATERNITY     2860
FINEBRANDSHOP            2712
O'NEILL                  2640
SMARTWOOL                2616
DC                       2596
HUGO BOSS                2469
RAY-BAN                  2465
FOX                      2445
TRUE RELIGION            2404
FRUIT OF THE LOOM        2396
JONES NEW YORK           2306
HAGGAR                   2254
KENNETH COLE             2209
RALPH LAUREN             2142
ADIDAS                   2137
OAKLEY                   2135
ROXY                     2128
CALVIN KLEIN JEANS       2108
LEE                      2048
JOCKEY                   2001
ORVIS                    1906
JOE'S JEANS              1870
ANNE KLEIN               1804
IZOD                     1770
HOT TOPIC                1749
HUE                      1683
ED HARDY                 1630
PERRY ELLIS              1626
PATTY                    1596
ANNA-KACI                1575
Name: count, dtype: int64

In [17]:
initems_df['product_brand'].value_counts().sort_index(ascending=False).head(40)

product_brand
[BLANKNYC]                 228
ZUMBA FITNESS               43
ZULU LAX                    16
ZORREL                      41
ZOOT                       141
ZOO YORK                   379
ZONAL                       27
ZOCKS                       17
ZOBHA                       43
ZINKE                       21
ZIMMERLI OF SWITZERLAND    165
ZICAC                       17
ZEROXPOSUR                  88
ZEROGRAVITEE               108
ZERO RESTRICTION            46
ZENICHE                     28
ZENANA                      72
ZANEROBE                   260
YUUUP!                      18
YUMS                        29
YUMMIE TUMMIE               97
YUKON                       49
YOURTACK                    26
YOUNG & RECKLESS            11
YOU! LINGERIE               52
YOGACOLORS                 361
YOANA BARASCHI             112
YMID SELECT                 11
YMI                        195
YIMEI                       33
YELETE                     500
YALA DESIGNS                 4
YALA                        75
YAGO                        86
Y&G                        486
XTREME COUTURE             168
XSCAPE                      11
XPORT DESIGNS               35
XOXO                       184
XFY                        216
Name: count, dtype: int64

In [ ]:
#특수문자 처리
initems_df['product_brand'].value_counts().sort_index(ascending=True).head(40)

product_brand
!IT JEANS                    203
'47 BRAND                     18
007LINGERIE                   41
10 DEEP                       16
106SHADES                     66
12XLSHOP INC.                 15
180S                         347
1826                          23
1VEMOON                       45
1WORLDSARONG                  43
2(X)IST                     1034
2117 OF SWEDEN                22
2B BY BEBE                   943
2EROS                         12
2XU                          336
34 HERITAGE                   20
35 DEGREE BELOW               34
4-RTH                         44
5 SEASONS                     27
5.11                          16
525 AMERICA                   35
555 TURNPIKE                  78
55DSL                        121
575 DENIM                     25
626 BLUE                      24
66 NORTH                      36
686                           17
7 DIAMONDS                   281
7 FOR ALL MANKIND           2943
89TH &#X0026; MADISON         11
A CHRISTMAS STORY             21
A PEA IN THE POD             732
A SHORE FIT                   15
A-LINE                        21
A. BYER                      187
A.B.S. BY ALLEN SCHWARTZ      29
A:X ARMANI EXCHANGE         1214
ABBEY DAWN                    51
ABERCROMBIE & FITCH           77
ABINI                        276
Name: count, dtype: int64

In [19]:
import pandas as pd
import numpy as np
pro_df = pd.read_csv('products.csv')
pro_df

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,EBD58B8A3F1D72F4206201DA62FB1204,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,2EAC42424D12436BDD6A5B8A88480CC3,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,EE364229B2791D1EF9355708EFF0BA34,1
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women,00BD13095D06C20B11A2993CA419D16B,1
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women,F531DC20FDE20B7ADF3A73F52B71D0AF,1
...,...,...,...,...,...,...,...,...,...
29115,5676,12.42338,Pants & Capris,WHAT GOES AROUND COMES AROUND Women's Colette ...,What Goes Around Comes Around,24.17,Women,3A01FC0853EBEBA94FDE4D1CC6FB842A,10
29116,6538,13.67500,Shorts,WHAT GOES AROUND COMES AROUND Women's Mimi Shorts,What Goes Around Comes Around,25.00,Women,741A0099C9AC04C7BFC822CAF7C7459F,10
29117,6712,12.40000,Shorts,WHAT GOES AROUND COMES AROUND Women's Fifi Short,What Goes Around Comes Around,25.00,Women,5726DAF2C9EE0F955ECA58291C26D2F3,10
29118,6821,13.47500,Shorts,WHAT GOES AROUND COMES AROUND Women's Ferguson...,What Goes Around Comes Around,25.00,Women,BA0A4D6ECEA3E9E126DD3B6D77291C97,10
29119,7809,101.84100,Blazers & Jackets,WHAT GOES AROUND COMES AROUND Women's Bennet J...,What Goes Around Comes Around,249.00,Women,67C08C98984CC2BC4B9D1F0D2FE6726A,10

In [21]:
pro_df['brand'] = pro_df['brand'].str.upper()

In [24]:
pro_df['brand'].value_counts().sort_index(ascending=True).head(40)

brand
!IT JEANS                    13
'47 BRAND                     1
007LINGERIE                   3
10 DEEP                       1
106SHADES                     6
12XLSHOP INC.                 1
180S                         22
1826                          1
1VEMOON                       4
1WORLDSARONG                  3
2(X)IST                      56
2117 OF SWEDEN                1
2B BY BEBE                   63
2EROS                         1
2XU                          18
34 HERITAGE                   2
35 DEGREE BELOW               2
4-RTH                         2
5 SEASONS                     2
5.11                          1
525 AMERICA                   3
555 TURNPIKE                  4
55DSL                         7
575 DENIM                     1
626 BLUE                      2
66 NORTH                      2
686                           1
7 DIAMONDS                   15
7 FOR ALL MANKIND           176
89TH &#X0026; MADISON         1
A CHRISTMAS STORY             1
A PEA IN THE POD             46
A SHORE FIT                   1
A-LINE                        1
A. BYER                      10
A.B.S. BY ALLEN SCHWARTZ      2
A:X ARMANI EXCHANGE          65
ABBEY DAWN                    2
ABERCROMBIE & FITCH           5
ABINI                        14
Name: count, dtype: int64

In [22]:
#특수문자 처리
pro_df['name'].value_counts().sort_index(ascending=True).head(40)

name
!iT Jeans Junior's Billy Shorts                                  1
!iT Jeans Women's Bonaroo Slouch Shorts                          1
!iT Jeans Women's Bureau Trouser Denim Short                     1
!iT Jeans Women's Coachella Canyon Stretch Shorts                1
!iT Jeans Women's Coachella Palooza Shorts                       1
!iT Jeans Women's Coachella Shorts                               1
!iT Jeans Women's Curvy Slim Boot Jean                           2
!iT Jeans Women's Curvy Stiletto Jean                            2
!iT Jeans Women's Harvest Crop Jean                              1
!iT Jeans Women's Skinny Micro Printed Corduroy                  1
#5098 Satin V-neck Bridemaid Prom Formal Long Gown               1
#7701 Halter Corset Bodice Bridesmaids Evening Formal Dress      1
#7716 One Shoulder Chiffon Homecoming Bridesmaids Party Dress    1
'Sexy Legs' Beaded Band Fashion Leggings                         1
'Sexy Legs' Beaded Paradise Fashion Leggings                     1
'Sexy Legs' Birch Tree Print Fashion Leggings                    1
'Sexy Legs' Black Cheetah Print Fashion Leggings                 1
'Sexy Legs' Black Jean Stretch Fashion Leggings                  1
'Sexy Legs' Black Leopard Print Fashion Leggings                 1
'Sexy Legs' Bobcat Print Fashion Leggings                        1
'Sexy Legs' Dot Print Fashion Leggings                           1
'Sexy Legs' Elliptical Pattern Fashion Leggings                  1
'Sexy Legs' Exotic Print Fashion Leggings                        1
'Sexy Legs' Floral Print Fashion Leggings                        1
'Sexy Legs' Loop Print Fashion Leggings                          1
'Sexy Legs' Lovesome Black Leather Fashion Leggings              1
'Sexy Legs' Lovey-Dovey Black Leather Fashion Leggings           1
'Sexy Legs' Ruffle Bottom Fashion Leggings                       1
'Sexy Legs' Side Runner Fashion Leggings                         1
'Sexy Legs' Stylized Blue Jean Fashion Leggings                  1
'Sexy Legs' Tattered Blue Jean Fashion Leggings                  1
'Sexy Legs' Tiger Print Fashion Leggings                         1
'Sexy Legs' Watercolor Floral Fashion Leggings                   1
(1272) Ladies Wide Leg Smart City Trousers Light Brown           1
(1272) Wide Leg Smart Soft City Trousers Black                   1
(1279) Skinny Trousers Military Army Look Camourflage            1
(2328) Satin Pencil Skirt with Skinny Belt Purple                1
(2382) Waist Detail Pencil Skirt Shadow Stripe                   1
(2384) Fishtail Flute Skirt with Free Skinny Belt Beige          1
(2384) Fishtail Peplum Hem Pencil Skirt Black                    1
Name: count, dtype: int64

In [ ]:
#특수문자 처리
pro_df['name'].value_counts().sort_index(ascending=False).head(40)

name
Â Â Exclusive Hawaiian Tropic Sunset In Paradise Aloha Shirt                                                  1
Â Â Exclusive Hawaiian Sunset In Paradise Aloha Shirt                                                         1
Â Â Exclusive Hawaiian Orchid (100% cotton) Aloha Shirt                                                       1
Â Â Exclusive Hawaiian Flowers In Paradise Aloha Shirt                                                        1
Â Â Exclusive Hawaiian All New Hibiscus In Paradise Aloha Shirt                                               1
white Half slip Culotte Underworks Pettipants nylon for women plus size trim double lace knickers Lingerie    1
under.me The Leggings                                                                                         1
tokidoki X Marvel Women Retro Spidey Dark Red Hoody                                                           1
tokidoki X Marvel Women Captain Kitty Hoodie                                                                  1
tokidoki The Marvel Pop Zip Hoody in Dark Gray Heather                                                        1
tokidoki Team Toki Women's Hoodie                                                                             1
tokidoki Prisma Women's Hoodie                                                                                1
tokidoki Ollie Women's Hoody                                                                                  1
tokidoki Bejeweled Women's Hoodie                                                                             1
tokidoki 80's Retro Women's Hoodie                                                                            1
tabbisocks Women's Wool Leg Warmers                                                                           1
tabbisocks Woman's Solid Color Arm Warmers                                                                    1
prAna Women's Tori Jacket                                                                                     1
prAna Women's Sylvie Jacket                                                                                   1
prAna Women's Sydney Sweater Dress                                                                            1
prAna Women's Satori Pant                                                                                     1
prAna Women's Monarch Convertible Pant                                                                        1
prAna Women's Lolita Pant                                                                                     1
prAna Women's Lined Boyfriend Jean                                                                            1
prAna Women's Kira Top                                                                                        1
prAna Women's Kari Jacket                                                                                     2
prAna Women's Julz Hoodie Top                                                                                 1
prAna Women's Gabby Duster                                                                                    1
prAna Women's Essex Pant                                                                                      1
prAna Women's Diva Vest                                                                                       1
prAna Women's Bliss Capri                                                                                     1
prAna Women's Audrey Pant                                                                                     1
prAna Women's Ashley Legging                                                                                  1
prAna Women's Amelia Top                                                                                      1
prAna Women's Amaya Dress                                                                                     1
prAna Men's Sutra Pant                                                                                        2
prAna Men's Stretch Zion Short                                                                                1
prAna Men's Stretch 32-Inch Inseam Zion Pant                                                                  1
prAna Men's Stretch 30-Inch Inseam Zion Pant                                                                  1
prAna Men's Sherpa Crew Tee                                                                                   1
Name: count, dtype: int64

In [30]:
pro_df['name'].value_counts(ascending=False).head(40)

name
Wrangler Men's Premium Performance Cowboy Cut Jean                   8
Thorlo Unisex Experia Running Sock                                   5
Puma Men's Socks                                                     5
Pearl iZUMi Attack Sock 3-Pack                                       5
Wrangler Men's Rugged Wear Classic Fit Jean                          5
7 For All Mankind Men's Standard Classic Straight Leg Jean           5
True Religion Men's Ricky Straight Jean                              5
Fruit of the Loom Women's 6-Pack Crew Socks                          5
Chaps Big and Tall Solid V-Neck Vest                                 4
Levi's Juniors' Demi Curve ID Skinny Jean                            4
Hanes Men's 4 Pack Boxer Brief                                       4
HUGO BOSS Men's Long Pant                                            4
Volcom Men's Vorta Slim Straight Leg Fit Jean                        4
Motherhood Maternity: 3 Pack Maternity Bikini Panties                4
FULL TILT Basic Womens Hoodie                                        4
Lucky Brand Mens Men's 361 Vintage Straight Denim Jean               4
Wigwam F1057 King Cotton High                                        4
Columbia Women's Fast Trek Ii Full Zip Fleece Jacket                 4
Wrangler Men's Wrancher Dress Jean                                   4
Wrangler Men's Original Cowboy Cut Relaxed Fit Jean                  4
Wrangler Men's Genuine Tampa Cargo Short                             4
KAMALIKULTURE Women's Long Sleeve Side Draped Dress                  4
Lilly Pulitzer Women's Callahan Short                                4
Hollywood Solid Pashmina Scarf                                       4
Michael Kors Men's 3 Pack Brief                                      3
Ray-Ban Unisex RB4034P Sunglasses                                    3
Silver Jeans Men's Zac Relaxed Fit Jean                              3
Ray-Ban Aviator Large Metal Sunglasses                               3
Silver Jeans Men's Grayson Relaxed Fit Jean                          3
Ray-Ban RB 2132 822/78 New Wayfarer Blue Gradient Polarized          3
Ray Ban RB3447 Unisex Icons Sunglasses - Choice of Frame and Lens    3
Ray-Ban RB4141 Round Wayfarer Sunglasses                             3
Ray Ban 4057 Sidestreet                                              3
Hanes Women's Cushion Extra Low Cut # 650/6                          3
ASICS Unisex Adult Thrmopolis LT Beanie                              3
HANES Sport Women's Low Cut Socks - 6 Pairs - 415/6                  3
Smartwool NEW Women's PhD Outdoor Light Mini with ReliaWool          3
DICKIES Mens Relaxed Fit Shorts                                      3
Champion Women's Zip Tech Bra                                        3
Anita Women's Momentum Sport Bra                                     3
Name: count, dtype: int64

In [29]:
pro_df['name'].value_counts(ascending=True).head(40)

name
Mini French Manicure                                                                   1
Marshmallow Robe - Lavender                                                            1
Leopard Lounge Pajamas                                                                 1
Aged to Perfection Pajamas                                                             1
Ruby Velour Robe                                                                       1
Snuggle Fleece (TM) Lavender Zebra Pajamas                                             1
Cinnamon Satin Pajamas                                                                 1
Cabernet Cashmere Lounge Set                                                           1
Dog Tired Pajamas for Men                                                              1
Stewart Plaid Flannel Robe for Men                                                     1
Crossword Pajamas for Men                                                              1
Stewart Plaid Button-Down Pajamas for Men                                              1
Cambridge Pajamas for Men                                                              1
Tartan Plaid Thermal Top Pajamas for Men                                               1
Men's Pinstripe Pajamas                                                                1
Harris Tweed Wool Jacket-Dougal Limited Edition                                        1
Women's Strapless Tunic Romper with layered design and zippered back closure           1
Hard Tail python leggings                                                              1
Enzyme Regular Solid Army Caps-Black W35S45D                                           1
Enzyme Regular Solid Army Caps-Olive W35S45D (One Size)                                1
Washed Canvas Ivy Cap - Black W11S64C                                                  1
4 Panel Large Bill Flap Hat W15S48B (One Size Fits Most/Khaki)                         1
Low Profile Dyed Cotton Twill Cap - Black W39S55D                                      1
Low Profile Dyed Cotton Twill Cap - Khaki W39S55D                                      1
Fishing Hat (01)-Khaki W10S32F                                                         1
Fashion Plaid Ivy Cap - Blue W10S69F                                                   1
Washed Hunting Fishing Outdoor Hat-Camo W11S41D                                        1
Womens MW Tankini Boyshorts Swimsuit Swimwear Crisscross Back Multiple Prints S-xxl    1
Mw Long Ruffle Tankini Bikini Swimsuit Bra Straps Multiple Prints                      1
Womens long tankini bikini swimsuit Marina West 2 piece multiple prints bra straps     1
Womens MW Tankini Boyshorts Swimsuit Swimwear Fashion prints S-XXL                     1
WHAT GOES AROUND COMES AROUND Women's Colette Pants                                    1
2XU Men's Swimmers Compression Long Sleeve Top                                         1
AGB Women's Long Sleeve Striped Sweater Dress                                          1
AGB Women's Short Sleeve Cowl Necked Sweater Dress                                     1
AGB Women's Striped Long Sleeve Sweater Dress With Sash                                1
AGB Women's V-Neck Dress With Draped Side                                              1
AGB Women's Plus-Size Ruched Short Sleeve V-Neck Dress with Empire Waistline           1
AGB Women's Solid Challis Palazzo Pant With Self Sash                                  1
BKE Women's Casual Linen Cotton Natural Comfortable Pants                              1
Name: count, dtype: int64